### ISSUE TITLE
Consider changing emoji to ⛑ (approximation of red hat).

### ISSUE THREAD

**Issue by hasparus** [drcmda/zustand#1]
I couldn't stop myself from starring this. Amazing project name.

I'd like to propose a feature.

⛑ is probably the closest emoji to the [popular red hat](https://i.ebayimg.com/images/g/8SwAAOSwHnFV120m/s-l640.jpg) so it may be a fitting choice for GitHub description emoji.

Sorry for a spam issue 😅

---

BTW

Isn't `useState` here a typo?
https://github.com/drcmda/msga/blame/master/readme.md#L32
It selects actions from the store so it looks like `useStore` used four lines above.

**Comment by drcmda** [comment]
I ... thought about this actually, but don't you think people will rip me to pieces? I'm not an american, are people ok with stuff like this? 😅

**Comment by drcmda** [comment]
And yes, it was a typo.

**Comment by hasparus** [comment]
Well... I've been thinking that using a flag unicode and a ⛑️ is certainly too much and not cool because flags are not rendered everywhere :c

Emojipedia says it's _"Rescue Worker’s Helmet"_, so it may even be fitting without a political reference.
Thinking about it again, it's not be the best idea :c
