### ISSUE TITLE
Some examples on how to separate actions/state in different modules

### ISSUE THREAD

**Issue by bernatfortet** [drcmda/zustand#13]
I'm considering using zustand for a large project and I'm curious about your thoughts on how separate responsibilities.

I liked how using redux I could have an actions file where each functions would be imported and composed. The issue is that the `set` is not accessible then, right?

**Comment by vikasaditya** [comment]
you can add actions like this to one or many files
say myActions.js

```
const actions = set => {
  return {
    dec: id =>
      set(
        produce(draft => {
          draft.counters[id].count = draft.counters[id].count - 1;
        })
      ),
    dispatch: args => {
      console.log("Dispatched", args);
      return set(state => reducer(state, args));
    }
  };
};

export default actions;
```
import in your store and init like

```
 
const [useStore] = create((set, get) => ({
  ...initialState,
  actions: actions(set)
}));
```

**Comment by drcmda** [comment]
Yes, like vikasaditya said, it’s fully customizable. You can get full Redux semantics
If you want.

**Comment by bernatfortet** [comment]
Thanks

**Comment by zbeyens** [comment]
[zustood](https://github.com/udecode/zustood) provides a pattern separating the state, the selectors and the actions
