### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by reflog** [drcmda/zustand#3]
Hi! Love the library, really fits my workflow, thank you!
I wrote some basic type-defs to help along, maybe you'll find them useful:

```typescript
type ZustandCreate<T> = (set) => T;
type ZustandUse<T> = (store: T) => Partial<T>;
declare module "zustand" {
  function create<T>(fn: ZustandCreate<T>): ZustandUse<T>[];
  export = create;
}
```

**Comment by reflog** [comment]
nm, it's still buggy. will reopen when it works fine :)

**Comment by bernatfortet** [comment]
Thanks for working on this! I'd love to get these typings as well
