### ISSUE TITLE
[rant] make the api better

### ISSUE THREAD

**Issue by avierr** [drcmda/zustand#4]
The API feels so 2015!

I really like the API provided by react-easy-state https://github.com/solkimicreb/react-easy-state and also some similar newer libraries. They just gets out of your way and you feel like you are doing normal javascript.

**Comment by drcmda** [comment]
I don't like hocs, implicit wraps, observables and mutation. I needed a simple plain javascript, plain object flux store with central actions and hooks. But of course, i'm not forcing anyone to use this.
