### ISSUE TITLE
[BUG] changing a state item with null fails to reload component

### ISSUE THREAD

**Issue by bernatfortet** [drcmda/zustand#5]
I'm not sure if I'm doing something wrong, but when I change state with a null value it fails to reload

Repro Steps:
- https://codesandbox.io/s/xlqk4yoqvz
- click show => shows text
- click hide => hides text
- click show
- click hide with null => text doesn't hide

**Comment by drcmda** [comment]
sigh, javascript

   typeof null === 'object' // true

i'll fix it later on, it's crashing trying to run Object(selected).entries, selected being "null".

**Comment by drcmda** [comment]
it's fixed and published: 0.0.5
